SET timezone = 'Europe/Helsinki';

CREATE TABLE IF NOT EXISTS users (
	id SERIAL NOT NULL PRIMARY KEY,
	username VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS movies (
	id SERIAL NOT NULL PRIMARY KEY,
	movie_path VARCHAR(255) NOT NULL,
	size VARCHAR(255) NOT NULL,
	downloaded BOOLEAN DEFAULT false NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
