SET timezone = 'Europe/Helsinki';

CREATE TABLE IF NOT EXISTS users (
	id SERIAL NOT NULL PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	username VARCHAR(255) NOT NULL,
	firstname VARCHAR(255) NOT NULL,
	lastname VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	verifycode VARCHAR(255) NOT NULL,
	status INT DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS profile_pics (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL,
	path TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
	-- , FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS movies (
	id SERIAL NOT NULL PRIMARY KEY,
	movie_path VARCHAR(255) NOT NULL,
	size VARCHAR(255) NOT NULL,
	downloaded BOOLEAN DEFAULT false NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS comments (
    id SERIAL NOT NULL PRIMARY KEY,
    movie_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subtitles (
	id SERIAL NOT NULL PRIMARY KEY,
	imdb_code VARCHAR(255) NOT NULL,
	language VARCHAR(255) NOT NULL,
	path TEXT NOT NULL
);
